#Как этим пользоваться:
#В корне проекта создайте пустой текстовый файл changes.txt.
#Перед сборкой напишите туда своими словами, что изменилось. Например: "Добавил автоматическое гашение OLED-экрана через 15 минут бездействия."
#Нажимаете Build.
#Скрипт сам:
#Соберет прошивку.
#Положит в папку releases/ бинарник: firmware_v2.4.2.bin и текстовый файл release_v2.4.2.txt.
#Создаст или обновит в корне проекта красивый файл CHANGELOG.md, где хронологически будут храниться описания абсолютно всех ваших релизов!
#Автоматически сотрет текст из changes.txt, чтобы в следующий раз он был чистым.

import os
import gzip
import datetime
import subprocess

Import("env")

# ================= 1. АВТО-СЖАТИЕ WEB-ИНТЕРФЕЙСА В GZ =================
html_src = os.path.join("data", "index.html")
header_dst = os.path.join("src", "web_index_gz.h")

if os.path.exists(html_src):
    with open(html_src, "rb") as f_in:
        raw_data = f_in.read()
    
    # Сжимаем максимальным сжатием
    gz_data = gzip.compress(raw_data, compresslevel=9)
    raw_size = len(raw_data)
    gz_size = len(gz_data)
    ratio = (1.0 - (gz_size / raw_size)) * 100.0

    # Генерируем C++ header с массивом PROGMEM
    with open(header_dst, "w", encoding="utf-8") as f_out:
        f_out.write("// Auto-generated by version_bump.py. DO NOT EDIT DIRECTLY!\n")
        f_out.write("#pragma once\n#include <Arduino.h>\n\n")
        f_out.write(f"// Original: {raw_size} bytes -> GZIP: {gz_size} bytes ({ratio:.1f}% saved)\n")
        f_out.write(f"const uint32_t index_html_gz_len = {gz_size};\n")
        f_out.write("const uint8_t index_html_gz[] PROGMEM = {\n  ")
        
        for i, b in enumerate(gz_data):
            f_out.write(f"0x{b:02X}, ")
            if (i + 1) % 16 == 0:
                f_out.write("\n  ")
        f_out.write("\n};\n")

    print(f"\n>>> [WEB GZIP COMPRESSOR] {html_src} ({raw_size} B) -> {gz_size} B ({ratio:.1f}% saved) <<<")
else:
    print(f"\n>>> [WARNING] {html_src} not found! Skipping GZIP generation. <<<")

# ================= 2. АВТО-ВЕРСИОНИРОВАНИЕ И CHANGELOG =================
version_file = "version.txt"
build_number = 1
major_version = "2.4"

if os.path.exists(version_file):
    with open(version_file, "r") as f:
        try:
            build_number = int(f.read().strip()) + 1
        except:
            build_number = 1

with open(version_file, "w") as f:
    f.write(str(build_number))

build_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
fw_version_str = f"v{major_version}.{build_number}"

changes_file = "changes.txt"
change_description = ""

if os.path.exists(changes_file):
    with open(changes_file, "r", encoding="utf-8") as cf:
        change_description = cf.read().strip()

if not change_description:
    try:
        git_log = subprocess.check_output(["git", "log", "-1", "--pretty=%B"]).decode('utf-8').strip()
        if git_log:
            change_description = f"Git: {git_log}"
    except:
        pass

if not change_description:
    change_description = "Maintenance build and performance optimizations."

print(f">>> [BUILD {fw_version_str}] Date: {build_date}")
print(f">>> [CHANGES] {change_description}\n")

env.Append(CPPDEFINES=[
    ("AUTO_FW_VERSION", f'\\"{fw_version_str}\\"'),
    ("AUTO_BUILD_DATE", f'\\"{build_date}\\"')
])

def after_build(source, target, env):
    build_dir = env.subst("$BUILD_DIR")
    bin_file = os.path.join(build_dir, "firmware.bin")
    releases_dir = "releases"
    if not os.path.exists(releases_dir):
        os.makedirs(releases_dir)
        
    out_bin = os.path.join(releases_dir, f"firmware_{fw_version_str}.bin")
    out_log = os.path.join(releases_dir, f"release_{fw_version_str}.txt")
    changelog_md = "CHANGELOG.md"
    
    if os.path.exists(bin_file):
        import shutil
        shutil.copyfile(bin_file, out_bin)
        with open(out_log, "w", encoding="utf-8") as log:
            log.write(f"Reflow Plate Firmware Release\n")
            log.write(f"Version:     {fw_version_str}\n")
            log.write(f"Date:        {build_date}\n")
            log.write(f"Description: {change_description}\n")
            log.write("------------------------------------------\n")
            log.write(f"Binary: {out_bin}\n")

        old_changelog = ""
        if os.path.exists(changelog_md):
            with open(changelog_md, "r", encoding="utf-8") as f_old:
                old_changelog = f_old.read()

        new_entry = f"## [{fw_version_str}] — {build_date}\n- {change_description}\n\n"
        with open(changelog_md, "w", encoding="utf-8") as f_new:
            f_new.write(new_entry + old_changelog)
            
        if os.path.exists(changes_file):
            with open(changes_file, "w", encoding="utf-8") as cf:
                cf.write("")

        print(f">>> [SAVED] Firmware: {out_bin}")
        print(f">>> [UPDATED] Log:    {changelog_md}\n")

env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", after_build)